// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'image': string;
  'name': string;
}
declare var cssExports: CssExports;
export = cssExports;
